### ISSUE TITLE
Sonos control

### ISSUE THREAD

**Issue by komtx** [jianyu-li/yet-another-media-player#7]
Anyway to tweak yaml to have volume slider control Sonos soundbar instead of TV?

**Comment by jianyu-li** [comment]
@komtx Great timing! I have been working on this and your issue gave me the drive to push it out. You can now specify a separate volume entity using volume_entity. Keep in mind that if you add a new entity via the ui then your custom YAML will be wiped out (working on this). So once you start using YAML I recommend always using YAML for now

### Example config

```yaml
type: custom:yet-another-media-player
entities:
  - entity_id: media_player.living_room_apple_tv
    volume_entity: media_player.living_room_sonos
volume_mode: slider
match_theme: true
```

You can download the latest v16.0.0 to get the update!
